// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nitswiudzcgeznihzjch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pdHN3aXVkemNnZXpuaWh6amNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjM2MzcsImV4cCI6MjA2NDQzOTYzN30.5GXZNJdp_fKRJVt4GshtaBJOEiifCSQD7c2Y99ElOI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);